---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# With special thanks and credit to the awesome Lumaeris: https://github.com/Lumaeris/vedaos/blob/main/recipes/recipe.yml
# Notes: Intel and NVIDIA stuff removed.

name: unwritten
description: This is the excellent VedaOS with some personal customizations.
base-image: quay.io/fedora/fedora-bootc
image-version: 43
cosign-version: none
nushell-version: none
blue-build-tag: none

modules:
  # install fedora logos and dnf5-plugins that is needed for copr management and other actions
  - type: dnf
    install:
      packages:
        - fedora-logos
        - dnf5-plugins

  # copying system files over to the system
  - type: files
    files:
      - source: system
        destination: /

  # remove leftovers from fedora-bootc
  - type: dnf
    remove:
      packages:
        - console-login-helper-messages
        - chrony
        - sssd*
        - qemu-user-static*
        - toolbox

  # footgun. see https://github.com/ublue-os/main/issues/598
  - type: script
    snippets:
      - rm -f /usr/bin/chsh /usr/bin/lchsh

  # add fedora-multimedia and disable openh264 repo
  - type: script
    snippets:
      - dnf5 config-manager addrepo --from-repofile='https://negativo17.org/repos/fedora-multimedia.repo'
      - dnf5 config-manager setopt fedora-multimedia.priority=90
      - dnf5 config-manager setopt fedora-cisco-openh264.enabled=0
  
  # install packages from fedora-multimedia
  - type: dnf
    install:
      skip-unavailable: true
      packages:
        - libheif
        - libva
        - mesa-dri-drivers
        - mesa-filesystem
        - mesa-libEGL
        - mesa-libGL
        - mesa-libgbm
        - mesa-va-drivers
        - mesa-vulkan-drivers
        - ocl-icd

  # lock rpms from fedora-multimedia
  - type: script
    snippets:
      - dnf5 versionlock add intel-gmmlib intel-mediasdk intel-vpl-gpu-rt libheif libva libva-intel-media-driver mesa-dri-drivers mesa-filesystem mesa-libEGL mesa-libGL mesa-libgbm mesa-va-drivers mesa-vulkan-drivers

  # install so called "batteries" coined by ublue
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
    install:
      packages:
        - fedora-repos-archive
        - zstd
        - alsa-firmware
        - apr
        - apr-util
        - distrobox
        - fdk-aac
        - ffmpeg
        - ffmpeg-libs
        - ffmpegthumbnailer
        - flatpak-spawn
        - fuse
        - fzf
        - google-noto-sans-balinese-fonts
        - google-noto-sans-cjk-fonts
        - google-noto-sans-javanese-fonts
        - google-noto-sans-sundanese-fonts
        - grub2-tools-extra
        - heif-pixbuf-loader
        - htop
        - intel-vaapi-driver
        - just
        - libavcodec
        - libcamera
        - libcamera-gstreamer
        - libcamera-ipa
        - libheif
        - libcamera-tools
        - libfdk-aac
        - libimobiledevice-utils
        - libratbag-ratbagd
        - libva-utils
        - lshw
        - net-tools
        - nvme-cli
        - nvtop
        - openrgb-udev-rules
        - openssl
        - pam-u2f
        - pam_yubico
        - pamu2fcfg
        - pipewire-libs-extra
        - pipewire-plugin-libcamera
        - powerstat
        - smartmontools
        - solaar-udev
        - squashfs-tools
        - symlinks
        - tcpdump
        - tmux
        - traceroute
        - usbmuxd
        - wireguard-tools
        - wl-clipboard
        - xhost
        - xorg-x11-xauth

  - type: script
    scripts:
      - swap-kernel.sh

  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        - flatpak
        - tailscale
        - NetworkManager-adsl
        - gdm
        - gnome-bluetooth
        - gnome-color-manager
        - gnome-control-center
        - gnome-initial-setup
        - gnome-remote-desktop
        - gnome-session-wayland-session
        - gnome-settings-daemon
        - gnome-shell
        - gnome-user-docs
        - gvfs-fuse
        - gvfs-goa
        - gvfs-gphoto2
        - gvfs-mtp
        - gvfs-smb
        - libsane-hpaio
        - nautilus
        - orca
        - ptyxis
        - sane-backends-drivers-scanners
        - xdg-desktop-portal-gnome
        - xdg-user-dirs-gtk
        - yelp-tools
        - plymouth
        - plymouth-system-theme
        - systemd-container
        - libcamera-v4l2
        - NetworkManager-wifi
        - atheros-firmware
        - brcmfmac-firmware
        - iwlegacy-firmware
        - iwlwifi-dvm-firmware
        - iwlwifi-mvm-firmware
        - mt7xxx-firmware
        - nxpwireless-firmware
        - realtek-firmware
        - tiwilink-firmware
        - alsa-firmware
        - alsa-sof-firmware
        - alsa-tools-firmware
        - gnome-disk-utility
        - uupd
        - unzip
        - adw-gtk3-theme
        - glibc-all-langpacks
        - wget
        - jetbrains-mono-fonts-all
        - fuse-libs
        - squashfuse-libs
        - glycin-thumbnailer
        - fira-code-fonts
        - hyfetch
        - fastfetch
        - jmtpfs
        - NetworkManager-config-connectivity-fedora
        - NetworkManager-openvpn
        - NetworkManager-wwan
        - cups
        - fprintd
        - fprintd-pam
        - hplip
        - hyperv-daemons
        - ibus
        - libratbag-ratbagd
        - open-vm-tools
        - open-vm-tools-desktop
        - pcsc-lite
        - qemu-guest-agent
        - systemd-oomd-defaults
        - whois
        - wireguard-tools
        - zram-generator-defaults
        - thermald
        - gum
        - borgbackup
        - btop
        - btrbk
        - chezmoi
        - clamav
        - clamav-freshclam
        - deadbeef
        - deadbeef-mpris2-plugin
        - deadbeef-plugins
        - firefox
        - gamemode
        - gnome-shell-extension-caffeine
        - gnome-shell-extension-gsconnect
        - inxi
        - libcap-ng-devel
        - mbuffer
        - micro
        - mpv
        - mpv-mpris
        - papers
        - procps-ng-devel
        - pv
        - tealdeer
        - xwininfo
    remove:
      packages:
        - gnome-tour
        - ibus-libpinyin
        - ibus-typing-booster
        - malcontent-control
        - yelp
        - yelp-libs
        - yelp-xsl
      exclude:
        - gnome-tour

  # get some system files from bluefin. gum is required which is installed on previous step
  - type: copy
    from: ghcr.io/projectbluefin/common:latest
    src: /system_files/shared/usr/bin/luks*
    dest: /usr/bin
  - type: copy
    from: ghcr.io/projectbluefin/common:latest
    src: /system_files/shared/usr/lib/dracut/fido*
    dest: /usr/lib/dracut
  - type: copy
    from: ghcr.io/projectbluefin/common:latest
    src: /system_files/shared/usr/lib/udev
    dest: /usr/lib/udev
  - type: copy
    from: ghcr.io/projectbluefin/common:latest
    src: /system_files/shared/usr/lib/modprobe.d/amd*
    dest: /usr/lib/modprobe.d
  - type: copy
    from: ghcr.io/projectbluefin/common:latest
    src: /system_files/bluefin/usr/lib/systemd/user/bazaar*
    dest: /usr/lib/systemd/user

  # install some backgrounds
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/bazzite
    install:
      packages:
        - f43-backgrounds-gnome
        - git

  # install gnome extensions
  - type: gnome-extensions        
    install:
      - 7065 # Tiling Shell
      - 517 # Caffeine
      - 615 # AppIndicator and KStatusNotifierItem Support      

  # install steam
  - type: dnf
    install:
      packages:
        - steam

  # set new os-release values
  - type: os-release
    properties:
      ID: unwritten
      ID_LIKE: fedora
      NAME: Unwritten
      VERSION: 43 (Next)
      PRETTY_NAME: Unwritten 43
      DEFAULT_HOSTNAME: unwritten
      VERSION_CODENAME: Next

  # add flathub, a way better flatpak repo, and remove fedora flatpaks
  - type: script 
    snippets:
      - mkdir -p /etc/flatpak/remotes.d/
      - curl --retry 3 -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo
      - rm -f /usr/lib/systemd/system/flatpak-add-fedora-repos.service

  # some finishing touches
  - type: script
    snippets:
      - rm -rf /usr/share/doc
      - rm -rf /usr/src
      - rpm --erase --nodeps kernel-cachyos-devel || true
      - rpm --erase --nodeps kernel-cachyos-lts-devel || true
      - rm -f /tmp/ltsbuild
      - dnf5 versionlock clear
      - dnf5 clean all

  # enable systemd services
  - type: systemd
    system:
      enabled:
        - gdm.service
        - systemd-timesyncd.service
        - systemd-resolved.service
        - tailscaled.service
        - uupd.timer
        - flatpak-add-flathub-repos.service
        - input-remapper.service
        - rechunker-group-fix.service
        - nvctk-cdi.service
      disabled:
        - rpm-ostree-countme.timer
      masked:
        - bootc-fetch-apply-updates.timer
        - bootc-fetch-apply-updates.service
    user:
      enabled:
        - bazaar.service

  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

# With special thanks and credit to the awesome Lumaeris: https://github.com/Lumaeris/vedaos/blob/main/recipes/recipe.yml      
