---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

###########################################################################################################################################################
## WITH SPECIAL THANKS AND CREDIT TO THE AWESOME ==== LUMAERIS ==== OF ==== VEDAOS ====: https://github.com/Lumaeris/vedaos/blob/main/recipes/recipe.yml ##     
###########################################################################################################################################################

################################################
## Find a removal log at the end of this file.##
################################################

name: unwritten
description: This is the excellent VedaOS with some personal customizations.
base-image: quay.io/fedora/fedora-bootc
image-version: 43
cosign-version: none
nushell-version: none
blue-build-tag: none

modules:
  # install fedora logos and dnf5-plugins that is needed for copr management and other actions
  - type: dnf
    install:
      packages:
        - fedora-logos
        - dnf5-plugins

  # copying system files over to the system
  - type: files
    files:
      - source: system
        destination: /

  # remove leftovers from fedora-bootc
  - type: dnf
    remove:
      packages:
        # - console-login-helper-messages
        - chrony                           # replaced with systemd-timesyncd (see below)
        - sssd*                            # not needed if only local users are used
        - qemu-user-static*                # not needed unless cross-arch dev is required
        - toolbox                          # replaced by distrobox (see below)

  # footgun. see https://github.com/ublue-os/main/issues/598
  - type: script
    snippets:
      - rm -f /usr/bin/chsh /usr/bin/lchsh

  # add fedora-multimedia and disable openh264 repo
  - type: script
    snippets:
      - dnf5 config-manager addrepo --from-repofile='https://negativo17.org/repos/fedora-multimedia.repo'
      - dnf5 config-manager setopt fedora-multimedia.priority=90
      - dnf5 config-manager setopt fedora-cisco-openh264.enabled=0
  
  # install packages from fedora-multimedia
  - type: dnf
    install:
      skip-unavailable: true
      packages:
        - libheif         
        - libva
        - mesa-dri-drivers
        - mesa-filesystem
        - mesa-libEGL
        - mesa-libGL
        - mesa-libgbm
        - mesa-va-drivers
        - mesa-vulkan-drivers
        - ocl-icd

  # lock rpms from fedora-multimedia
  - type: script
    snippets:
      - dnf5 versionlock add intel-gmmlib intel-mediasdk intel-vpl-gpu-rt libheif libva libva-intel-media-driver mesa-dri-drivers mesa-filesystem mesa-libEGL mesa-libGL mesa-libgbm mesa-va-drivers mesa-vulkan-drivers

  # Install so called "batteries" coined by Universal Blue:
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
    install:
      packages:
        - alsa-firmware
        - distrobox
        - fdk-aac
        - fedora-repos-archive
        - ffmpeg
        - ffmpeg-libs
        - ffmpegthumbnailer
        - flatpak-spawn
        - fuse
        - fzf
        - google-noto-sans-balinese-fonts
        - google-noto-sans-cjk-fonts
        - google-noto-sans-javanese-fonts
        - google-noto-sans-sundanese-fonts
        - heif-pixbuf-loader
        - htop
        - libavcodec
        - libcamera
        - libcamera-gstreamer
        - libcamera-ipa
        - libcamera-tools
        - libfdk-aac
        - libheif
        - libratbag-ratbagd
        - libva-utils
        - lshw
        - nvme-cli
        - nvtop
        - openrgb-udev-rules
        - openssl
        - pipewire-libs-extra
        - pipewire-plugin-libcamera
        - powerstat
        - smartmontools
        - solaar-udev
        - squashfs-tools
        - symlinks
        - tcpdump
        - traceroute
        - wireguard-tools
        - wl-clipboard
        - xhost
        - xorg-x11-xauth
        - zstd

  - type: script
    scripts:
      - proton_vpn_app.sh
      - swap-kernel.sh
      - sudont.sh

  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
    install:
      packages:
        - adw-gtk3-theme
        - alsa-sof-firmware
        - alsa-tools-firmware
        - atheros-firmware
        - atuin
        - borgbackup
        - brcmfmac-firmware
        - btop
        - btrbk
        - chezmoi
        - clamav
        - clamav-freshclam
        - cups
        - fastfetch
        - f43-backgrounds-gnome
        - fira-code-fonts
        - firefox
        - firewalld
        - flatpak
        - fprintd
        - fprintd-pam
        - fuse-libs
        - gamemode
        - gdm
        - git
        - glibc-langpack-de
        - glibc-langpack-en
        - glibc-langpack-fr
        - glycin-thumbnailer
        - gnome-bluetooth
        - gnome-color-manager
        - gnome-control-center
        - gnome-disk-utility
        - gnome-initial-setup
        - gnome-session-wayland-session
        - gnome-settings-daemon
        - gnome-shell
        - gnome-shell-extension-caffeine
        - gnome-shell-extension-gsconnect
        - gum
        - gvfs-fuse
        - gvfs-gphoto2
        - gvfs-mtp
        - gvfs-smb
        - hplip
        - hyfetch
        - ibm-plex-sans-fonts
        - ibus
        - inxi
        - iwlwifi-dvm-firmware
        - iwlwifi-mvm-firmware
        - jetbrains-mono-fonts-all
        - jmtpfs
        - libcamera-v4l2
        - libratbag-ratbagd
        - libsane-hpaio
        - lynis
        - mangohud
        - mbuffer
        - micro
        - mpv
        - mpv-mpris
        - mt7xxx-firmware
        - nautilus
        - NetworkManager-config-connectivity-fedora
        - NetworkManager-openvpn
        - NetworkManager-wifi
        - nxpwireless-firmware
        - papers
        - ptyxis
        - pv
        - realtek-firmware
        - sane-backends-drivers-scanners
        - squashfuse-libs
        - systemd-container
        - systemd-oomd-defaults
        - tealdeer
        - tiwilink-firmware
        - unzip
        - wget
        - whois
        - xdg-desktop-portal-gnome
        - xdg-user-dirs-gtk
        - xwininfo
        - zram-generator-defaults
        - zsh
    
  # Linux Mint's webapp-manager from Kyle Gospo’s (Bazzite) repo:
  #- type: dnf
  #  repos:
  #    cleanup: true
  #    copr:
  #      - kylegospo/webapp-manager
  #  install:
  #    packages:
  #      - webapp-manager

  - type: dnf
    repos:
      cleanup: true
    remove:
      packages:
        - gnome-tour
        - ibus-libpinyin
        - ibus-typing-booster
        - malcontent-control
        - yelp
        - yelp-libs
        - yelp-xsl 
        
  # Steam:
  - type: dnf
    install:
      packages:
        - steam
  
  # GNOME extensions:
  - type: gnome-extensions        
    install:
      - 7065    # Tiling Shell
      - 615     # AppIndicator and KStatusNotifierItem Support
      # GSConnect  (installed as rpm package `gnome-shell-extension-gsconnect`, see above)
      # Caffeine   (installed as rpm package `gnome-shell-extension-caffeine`, see above)
       
  # DeaDBeeF (make sure these are the last rpm packages to be installed):
  - type: dnf
    repos:
      cleanup: true
      nonfree: rpmfusion
    install:
      packages:
        - deadbeef
        # - deadbeef-mpris2-plugin # currently causes issues (cursour stutters while skipping to the next song)
        - deadbeef-plugins
        
  # Set DeaDBeeF to dark theme:
  - type: script
    scripts:
      - deadbeef.sh
   
  # Stamp:
  - type: os-release
    properties:
      ID: unwritten
      ID_LIKE: fedora
      NAME: Unwritten
      VERSION: 43 (Next)
      PRETTY_NAME: Unwritten 43
      DEFAULT_HOSTNAME: unwritten
      VERSION_CODENAME: Next

  # add flathub, a way better flatpak repo, and remove fedora flatpaks
  - type: script 
    snippets:
      - mkdir -p /etc/flatpak/remotes.d/
      - curl --retry 3 -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo
      - rm -f /usr/lib/systemd/system/flatpak-add-fedora-repos.service

  # some finishing touches
  - type: script
    snippets:
      - rm -rf /usr/share/doc
      - rm -rf /usr/src
      - rpm --erase --nodeps kernel-cachyos-devel || true
      - rpm --erase --nodeps kernel-cachyos-lts-devel || true
      - rm -f /tmp/ltsbuild
      - dnf5 versionlock clear
      - dnf5 clean all

  # Systemd services:
  - type: systemd
    system:
      enabled:
        - gdm.service
        - systemd-timesyncd.service
        - systemd-resolved.service
        - rechunker-group-fix.service
        - me.proton.vpn.split_tunneling.service
        - btrbk.timer
      disabled:
        - rpm-ostree-countme.timer
      masked:
        - bootc-fetch-apply-updates.timer
        - bootc-fetch-apply-updates.service
    # user:
    #  enabled:
        # - some_service.service

  # Set kernel arguments for disabling plymouth (since it is not part of Unwritten):
  - type: kargs
    kargs:
      - plymouth.enable=0
      - rd.plymouth=0
      - rd.info=1

  # Set kernel arguments for Varmilo keyboard, so you don’t have to press the `FN` key to get `F1`–`F12` working:
  - type: kargs
    kargs:
      - hid_apple.fnmode=2

  - type: initramfs

 # this sets up the proper policy & signing files for signed images to work fully:
  - type: signing 
  
##########################################
## My removal list for future reference:##
##########################################

# Lecacy commands like `ipconfig` and `route`:
  # - net-tools
  # Use `ip addr` or `ip link` instead.

# iOS support (iPhone, iPod Touch, iPad and Apple TV, etc.):
  # - usbmuxd
  # - libimobiledevice-utils

# Multi-factor authentification (YubiKey, etc.):
  # - pam-u2f
  # - pam_yubico
  # - pamu2fcfg

# Smart Card readers:
  # - pcsc-lite

# Apache Portable Runtime:
  # - apr
  # - apr-util

# More GRUB tools (usually not needed for bootc):
  # - grub2-tools-extra

# DSL modem and LTE/5G modem support:
  # - NetworkManager-adsl
  # - NetworkManager-wwan

# GNOME Connections support (for connections to YOUR device):
  # - gnome-remote-desktop

# GNOME manuals:
  # - gnome-user-docs

# GNOME Online Accounts:
  # - gvfs-goa

# Intel specific:
  # - intel-vaapi-driver
  # - intel-gmmlib
  # - intel-mediasdk
  # - intel-vpl-gpu-rt
  # - intel-audio-firmware
  # - libva-intel-media-driver
  # PREVENTS OVERHEATING IN INTEL LAPTOPS:
  # - thermald 

# Virtualization Guest Tools:
  # - hyperv-daemons
  # - qemu-guest-agent
  # - open-vm-tools
  # - open-vm-tools-desktop

# Tools for creating GNOME documentation:
  # - yelp-tools

# For very old WLAN Cards:
  # - iwlegacy-firmware

# Steering Wheel Manager (Oversteer) input:
  # - oversteer-udev

# Support for ALL languages:
  # - glibc-all-langpacks

# For .justfile scripts:
  # - just
  
# Terminal multiplexer:
  # - tmux

# Text-to-speech:
  # - orca

# Universal Blue Update (automatic updates):
  # - uupd

# Header files for devs:
  # - libcap-ng-devel
  # - procps-ng-devel

# Homebrew support:
  # - brew-setup.service

# Custom kernel signing:
  # - akmods-keygen@akmods-keygen.service
  # - akmods-keygen.target

###########################################################################################################################################################
## WITH SPECIAL THANKS AND CREDIT TO THE AWESOME ==== LUMAERIS ==== OF ==== VEDAOS ====: https://github.com/Lumaeris/vedaos/blob/main/recipes/recipe.yml ##     
###########################################################################################################################################################
